In [ ]:
import pandas as pd
import numpy as np

In [ ]:
temp_df=pd.read_csv('/content/sample_data/IMDB Dataset.csv')

In [ ]:

df = temp_df.iloc[:10000]

In [ ]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(17)

In [ ]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_680/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
import re
def html(text):
  cleaned_text=re.sub('<.*?>','',text)
  return cleaned_text

In [ ]:
df['review']=df['review'].apply(html)

/tmp/ipykernel_680/484915717.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(html)

In [ ]:
df.loc[0]['review']

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [ ]:
df['review']=df['review'].apply(lambda x:x.lower())

/tmp/ipykernel_680/2697927567.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
/tmp/ipykernel_680/2699294292.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [ ]:
X=df.iloc[:,0:1]
y = df['sentiment']

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y=encoder.fit_transform(y)

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
X_train.shape

(7986, 1)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer()

In [ ]:
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(X_test_bow)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.6129193790686029

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)

RandomForestClassifier()

In [ ]:
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8442663995993991

In [ ]:
cv=CountVectorizer(max_features=3000)
X_train_bow=cv.fit_transform(X_train['review']).toarray()
X_test_bow=cv.transform(X_test['review']).toarray()

rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8352528793189785

In [ ]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8367551326990486

In [ ]:

from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:

tfidf = TfidfVectorizer()

In [ ]:

X_train_tfidf = tfidf.fit_transform(X_train['review']).toarray()
X_test_tfidf = tfidf.transform(X_test['review'])
rf = RandomForestClassifier()

rf.fit(X_train_tfidf,y_train)
y_pred = rf.predict(X_test_tfidf)

accuracy_score(y_test,y_pred)

0.8527791687531296

In [ ]:
!pip install gensim
import gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.3.0)
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 27.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

In [ ]:
# Remove stopwords

X_train = X_train['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))
# Remove stopwords

X_test = X_test['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [ ]:

import spacy
import en_core_web_sm

In [ ]:
nlp = en_core_web_sm.load()

In [ ]:
doc = nlp(X_train.values[0])
print(doc.vector)

[-6.81118891e-02 -3.46259981e-01 -5.24605885e-02 -3.28561366e-02
  3.84294800e-02  3.58647913e-01  3.52347910e-01  2.45472342e-01
  1.27676919e-01 -2.09005848e-01  4.31823343e-01 -2.37258106e-01
 -1.13569207e-01 -4.14077863e-02 -1.71494052e-01  1.88332289e-01
 -2.13954791e-01 -2.90296972e-01  2.15587050e-01 -2.59519339e-01
 -1.74422845e-01  3.28131288e-01 -1.56767085e-01  9.09932181e-02
  1.79211736e-01 -2.21681986e-02  1.43852383e-01  1.87706813e-01
  1.75378144e-01  1.55919462e-01  2.09047869e-01  6.01039380e-02
 -1.14290521e-01  1.19138569e-01 -2.06637591e-01 -6.00975826e-02
 -1.05833448e-01 -2.62093619e-02 -2.01058745e-01 -2.13665619e-01
 -2.57564396e-01  2.51570374e-01 -2.24459115e-02  2.24844754e-01
 -1.65547768e-04  1.95873052e-01 -1.06206186e-01  6.36125654e-02
  2.21009240e-01 -1.49474397e-01  1.45018041e-01  9.84441303e-03
 -9.46604237e-02 -2.06208572e-01 -9.64386202e-03 -4.62430948e-03
  3.04091461e-02 -1.98194999e-02  4.12794948e-02  7.67056197e-02
 -6.52771369e-02 -4.79460210e-02 -8.13585445e-02 -2.26950586e-01
 -6.55143932e-02  4.52552252e-02  1.99421436e-01 -1.49270460e-01
 -9.65528265e-02 -1.78865343e-01  1.24435060e-01  5.77306859e-02
 -6.33085892e-02 -3.57169837e-01  5.83990291e-02 -4.31006812e-02
 -3.31659406e-01  1.79621186e-02  5.44817895e-02 -2.09193453e-01
 -2.19871759e-01 -2.13130563e-02 -1.64778292e-01  3.53916399e-02
 -1.45721614e-01  5.88985533e-02  2.86158234e-01  1.45525277e-01
 -4.11685228e-01  3.03605080e-01 -1.35826707e-01  2.22357914e-01
  4.24646050e-01  2.51159757e-01 -8.94484296e-02  6.47448003e-02]

In [ ]:
!pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz

Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz
  ERROR: HTTP error 404 while getting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz
ERROR: Could not install requirement https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz because of HTTP error 404 Client Error: Not Found for url: https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz for URL https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.5.tar.gz

In [ ]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 26.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.